import { chromium, expect } from '@playwright/test';
import { mkdir } from 'node:fs/promises';
const browser = await chromium.launch({headless: true, channel: process.env.BROWSER_CHANNEL,
  args: ['--enable-unsafe-swiftshader']});
const base = process.env.VIEWER_URL || 'http://127.0.0.1:8139/';
try {
  const page = await browser.newPage({locale: 'ko-KR', viewport: {width: 1380, height: 1000}});
  const errors = [], requests = [];
  page.on('pageerror', error => errors.push(error.message));
  page.on('request', request => { if (request.url().includes('/collision/')) requests.push(request.url()); });
  await page.goto(new URL('/mantle/', base).href);
  expect(requests).toEqual([]);
  const opener = page.locator('[data-collision-open]');
  await opener.click();
  const dialog = page.locator('#collision-dialog');
  const popup = page.frameLocator('#collision-dialog iframe');
  await expect(dialog).toBeVisible();
  await expect(popup.locator('body')).toHaveAttribute('data-age', '80');
  await expect(popup.locator('#collision-surface')).toHaveAttribute('data-age', '80');
  await expect(popup.locator('#collision-surface')).toHaveAttribute('data-ve', '50');
  await expect(popup.locator('#crust-panel')).toHaveAttribute('data-thickness', '35.0');
  await expect(popup.locator('#collision-flow')).not.toBeChecked();
  await popup.locator('#collision-overview summary').click();
  await expect(popup.locator('#collision-map')).toBeVisible();
  await popup.locator('#collision-overview summary').click();
  const count = requests.filter(url => url.includes('/data/')).length;
  await popup.locator('#collision-time').fill('4');
  await expect(popup.locator('body')).toHaveAttribute('data-age', '0');
  await expect(popup.locator('#collision-surface')).toHaveAttribute('data-age', '0');
  await popup.locator('#surface-ve').selectOption('100');
  await expect(popup.locator('#collision-surface')).toHaveAttribute('data-ve', '100');
  const before = await popup.locator('#collision-section').evaluate(canvas => canvas.clientHeight);
  await popup.locator('#section-ve').selectOption('5');
  expect(await popup.locator('#collision-section').evaluate(canvas => canvas.clientHeight)).toBeGreaterThan(before*2);
  await popup.locator('#section-ve').selectOption('2');
  await popup.locator('#crust-ve').selectOption('20');
  await expect(popup.locator('#crust-panel')).toHaveAttribute('data-thickness', '70.0');
  await popup.locator('#collision-shortening').fill('0');
  await expect(popup.locator('#crust-panel')).toHaveAttribute('data-thickness', '35.0');
  await popup.locator('#collision-shortening').fill('1000');
  await popup.locator('#collision-flow').check();
  await popup.locator('#collision-mantle').uncheck();
  await popup.locator('#collision-mantle').check();
  await popup.locator('#collision-crust').uncheck();
  await expect(popup.locator('#crust-panel')).toBeHidden();
  await popup.locator('#collision-crust').check();
  expect(requests.filter(url => url.includes('/data/')).length).toBe(count);
  await mkdir('test-results', {recursive: true});
  await page.screenshot({path: 'test-results/collision-popup.png'});
  await popup.locator('#collision-crust-view').scrollIntoViewIfNeeded();
  await page.screenshot({path: 'test-results/collision-crust.png'});
  // Escape from inside the iframe closes the native dialog and restores focus.
  await popup.locator('#collision-time').press('Escape');
  await expect(dialog).not.toBeVisible();
  await expect(opener).toBeFocused();
  await expect(dialog.locator('iframe')).not.toHaveAttribute('src', /.+/);
  await opener.click();
  await expect(popup.locator('body')).toHaveAttribute('data-age', '80');
  await popup.locator('#collision-play').click();
  await expect(popup.locator('body')).toHaveAttribute('data-age', '60', {timeout: 5000});
  await dialog.locator('button').click();
  await page.setViewportSize({width: 390, height: 844});
  await opener.click();
  await expect(popup.locator('body')).toHaveAttribute('data-age', '80');
  expect(await popup.locator('body').evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({path: 'test-results/collision-mobile.png'});
  await dialog.locator('button').click();
  await page.goto(new URL('/lang/en/?next=/collision/', base).href);
  await expect(page.locator('h1')).toHaveText('India–Asia section A–A′');
  await expect(page.locator('body')).toHaveAttribute('data-age', '80');
  expect(errors).toEqual([]);
  console.log('Collision popup: lazy loading, source ages, scenario, toggles, playback, Escape/focus, mobile, English OK');
} finally { await browser.close(); }
