"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parents[2]


# Application definition

INSTALLED_APPS = [
    'core.apps.CoreAdminConfig',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core.apps.CoreConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# A single shared key that unlocks datasets whose licence does not permit publication.
# The site itself stays open; only those resources ask. Empty means they are not offered
# at all. See core/access.py.
ACCESS_KEY = os.environ.get('ACCESS_KEY', '')

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.template.context_processors.i18n',
                'core.context_processors.branding',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.environ.get('DATABASE_PATH', BASE_DIR / 'data' / 'db' / 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'ko'
# Korean is the source language; English comes from locale/en. The switch in the header
# sets the language cookie, and LocaleMiddleware reads it (then Accept-Language).
LANGUAGES = [('ko', '한국어'), ('en', 'English')]
LOCALE_PATHS = [BASE_DIR / 'locale']

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = Path(os.environ.get('STATIC_ROOT', BASE_DIR / 'staticfiles'))
MEDIA_URL = '/media/'
MEDIA_ROOT = Path(os.environ.get('MEDIA_ROOT', BASE_DIR / 'media'))
INTEGRITY_SENTINEL = Path(DATABASES['default']['NAME']).parent / 'INTEGRITY_FAIL'

# Where the segmentation's derived fields are read from. In a container this points at
# the read-only runtime bundle; locally it is the working copy the script writes.
SCOTESE_DERIVED_DIR = Path(os.environ.get(
    'SCOTESE_DERIVED_DIR', BASE_DIR / 'data' / 'derived' / 'segmentation'))

# The 2016 PaleoAtlas fields, from scripts/segment_paleoatlas.py. Same layout as above.
PALEOATLAS_DERIVED_DIR = Path(os.environ.get(
    'PALEOATLAS_DERIVED_DIR', BASE_DIR / 'data' / 'derived' / 'paleoatlas'))

# PaleoCoastlines (Kocsis & Scotese 2021) packed by scripts/pack_coastlines.py.
# The PaleoDEM elevation textures written by scripts/build_paleodem.py.
PALEODEM_DERIVED_DIR = Path(os.environ.get(
    'PALEODEM_DERIVED_DIR', BASE_DIR / 'data' / 'derived' / 'paleodem'))
PALEOCOASTLINES_DERIVED_DIR = Path(os.environ.get(
    'PALEOCOASTLINES_DERIVED_DIR', BASE_DIR / 'data' / 'derived' / 'paleocoastlines'))

# Which land masks the globe shows by default: 'paleoatlas2016' (the 2016 atlas, same
# edition as the PALEOMAP rotation model) or 'scotese2002' (the 2002 web maps). A page
# can still ask for the other with ?masks=, for comparison.
MASK_SOURCE = os.environ.get('MASK_SOURCE', 'paleoatlas2016')

# Where the packed EarthByte plate model is read from. Kept apart from the Scotese
# derivatives: different authors, different licence, different limits.
PLATE_MODEL_DIR = Path(os.environ.get(
    'PLATE_MODEL_DIR', BASE_DIR / 'data' / 'derived' / 'plates'))

# How the globe's timeline is sampled between the published maps.
#
# STEPS divides every gap into the same number of sub-steps, so a stop is a fraction of
# the way from one map to the next regardless of how much time that gap covers.
# INTERVAL_MA instead places a stop every so many million years, which makes the slider
# move at a constant rate through time; gaps that cover more time then get more stops.
# INTERVAL_MA wins when both are set. Either way the published map ages are always
# stops of their own, so the slider can still land on what the source actually drew.
#
# Both are kept as raw strings: core.globe.sampling() validates them against the
# choices, so a typo in the environment falls back instead of failing at import.
SCOTESE_VIEWER_STEP_CHOICES = (1, 2, 4, 8, 16, 32)
SCOTESE_VIEWER_INTERVAL_CHOICES = (0.5, 1.0, 2.0, 5.0, 10.0, 25.0)
SCOTESE_VIEWER_STEPS = os.environ.get('SCOTESE_VIEWER_STEPS', '4')
SCOTESE_VIEWER_INTERVAL_MA = os.environ.get('SCOTESE_VIEWER_INTERVAL_MA', '')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
